language: r
r:
 - 3.2
 - 3.3
 - oldrel
 - release
 - devel
 - bioc-devel

bioc_check: true

cache: packages

sudo: false

# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master

bioc_packages:
  - Biostrings
  - BiocManager

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

