# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

r:
  - release
  - devel
  - oldrel

# We need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

# download Biostrings from Bioconductor not Cran
bioc_packages:
  - Biostrings

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

install:

  - git clone --depth 1 https://github.com/r-lib/remotes && R CMD build --no-build-vignettes remotes && R CMD INSTALL remotes*tar.gz && rm -rf remotes remotes*tar.gz
  - R -e 'install.packages("curl")' -e 'remotes::install_deps(".", dependencies = TRUE)'
