language: r
sudo: false
cache: packages

r:
 - 3.2
 - 3.3
 - oldrel
 - release
 - devel
 - bioc-release

# We need to install BiocInstaller for testing Bioconductor packages
bioc_required: true


# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

